server:
  port: 52781

zuul:                                                 # 默认路由规则
  prefix: /api                                        # 路由前缀 所有携带 api 前缀的请求都经过网关路由
  sensitive-headers: Cookie,Set-Cookie,Authorization  #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true                               #设置为true重定向是会添加host请求头
  ignored-services:                                    #关闭默认路由配置
    - chat-service
    - pay-service
  routes:                                             # 每个服务配置路由
    chat-service:
      path: /chat-service/**                          # 聊天系统相关请求路由到聊天服务
    pay-service:
      path: /pay-service/**                           # 支付系统相关请求路由到支付服务
  SendErrorFilter:
    error:
      disable: true # 禁用 zuul 默认过滤器

hystrix:
  # 用于控制HystrixCommand的行为
  command:
    default:
      execution:
        isolation:
          thread:
            # 配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
            timeoutInMilliseconds: 1000

ribbon: # 使用Ribbon的配置来设置路由转发时请求连接及处理的超时时间
  # 服务请求连接超时时间（毫秒）
  ConnectTimeout: 1000
  # 服务请求处理超时时间（毫秒）
  ReadTimeout: 3000