feign:
  hystrix:
    enabled: true   # 在Feign中开启Hystrix
  compression:
    request:
      enabled: false                                        # 是否对请求进行GZIP压缩
      mime-types: text/xml,application/xml,application/json # 指定压缩的请求数据类型
      min-request-size: 2048                                # 超过该大小的请求会被压缩
    response:
      enabled: false                                        #是否对响应进行GZIP压缩
  client:
    config:
      default:
        connect-timeout: 5000      # 连接超时时间
        read-timeout: 5000         #
        logger-level: full

# 由于版本问题,该配置目前未生效,研究中. 暂时使用了 com.ghost.chat.gateway.loadbalancer.LoadbalancerConfig bean 配置方式
ribbon:
  restclient:
    enabled: true
  ConnectTimeout: 1000                                              # 服务请求连接超时时间（毫秒）
  ReadTimeout: 3000                                                 # 服务请求处理超时时间（毫秒）
  OkToRetryOnAllOperations: true                                    # 对超时请求启用重试机制
  MaxAutoRetriesNextServer: 2                                       # 换重试实例的最大个数
  MaxAutoRetries: 1                                                 # 切换实例后重试最大次数
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 修改负载均衡算法